openapi: "3.0.3"

info:
  title: Documentação Swagger API
  description: >
    Teste
  version: "1.0"

servers:
  - url: http://localhost:8080/v1

paths:
  /check_status:
    get:
      description: Retorna o status de um trabalho prévio
      operationId: controller.check_status
      parameters:
        - name: "job_id"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          #! TODO: implementar retorno das datas (start_date e end_date)
          description: Job's status
          content:
            "application/json":
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                  job_status:
                    type: string
        "400":
          description: >
            Requisição mal formatada. Por exemplo, ausência, na requisição, de algum 
            parâmetro obrigatório
        "401":
          description: Informação de autorização é inválida ou ausente.
        "404":
          description: Erro interno.
        "5XX":
          description: Erro inesperado.
  /calculate_ndvi:
    post:
      description: Recebe um intevalo de tempo e arquivo geojson e retorna o ndvi
      operationId: controller.calculate_ndvi
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                geojson:
                  type: string
                  format: binary
                  description: "Arquivo no formato GeoJson"
                dt_inicio:
                  type: string
                  description: "Data de início de intervalo de busca"
                dt_fim:
                  type: string
                  description: "Data de término de intervalo de busca"
                cobertura:
                  type: integer
                  description: "Porcentagem de conbertura de nuvens"
                client_id:
                  type: string
                  description: "Id para acesso a api copernicus"
                client_secret:
                  type: string
                  format: password
                  description: "Chave de acesso a api copernicus"
      responses:
        "200":
          description: >
            arquivo zipado com os planos de ensino assinados
          content:
            "application/json":
              schema:
                type: object
                properties:
                  jobid:
                    type: string
        "400":
          description: Requisição mal formatada. Por exemplo, ausência, na requisição, de algum parâmetro obrigatório
        "401":
          description: Informação de autorização é inválida ou ausente.
        "404":
          description: Job não encontrado na fila de trabalhos prontos.
        "5XX":
          description: Erro inesperado.